// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Origin.Models;
using System;

namespace Origin.Migrations.Origin
{
    [DbContext(typeof(OriginContext))]
    partial class OriginContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Origin.Models.Store.OR_Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid>("OriginId");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("OR_Forms");
                });

            modelBuilder.Entity("Origin.Models.Store.OR_Input", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid>("OriginId");

                    b.Property<Guid>("RelatedOriginId");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("OR_Inputs");
                });

            modelBuilder.Entity("Origin.Models.Store.OR_Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<Guid>("ItemTypeOriginId");

                    b.Property<DateTime>("LastEditDate");

                    b.Property<Guid>("OriginId");

                    b.HasKey("Id");

                    b.ToTable("OR_Items");
                });

            modelBuilder.Entity("Origin.Models.Store.OR_ItemAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("FormOriginId");

                    b.Property<Guid>("ItemTypeOriginId");

                    b.Property<string>("Name");

                    b.Property<Guid>("OriginId");

                    b.HasKey("Id");

                    b.ToTable("OR_ItemActions");
                });

            modelBuilder.Entity("Origin.Models.Store.OR_ItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid>("OriginId");

                    b.HasKey("Id");

                    b.ToTable("OR_ItemTypes");
                });

            modelBuilder.Entity("Origin.Models.Store.OR_Lookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid>("OriginId");

                    b.HasKey("Id");

                    b.ToTable("OR_Lookups");
                });

            modelBuilder.Entity("Origin.Models.Store.OR_LookupValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("OriginId");

                    b.Property<Guid>("RelatedOriginId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("OR_LookupValues");
                });

            modelBuilder.Entity("Origin.Models.Store.OR_Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid>("OriginId");

                    b.Property<Guid>("RelatedOriginId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("OR_Properties");
                });

            modelBuilder.Entity("Origin.Models.Store.OR_RoleTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AllowCreate");

                    b.Property<bool>("AllowDelete");

                    b.Property<bool>("AllowRead");

                    b.Property<bool>("AllowUpdate");

                    b.Property<Guid>("RoleId");

                    b.Property<string>("TableName");

                    b.HasKey("Id");

                    b.ToTable("OR_RoleTables");
                });
#pragma warning restore 612, 618
        }
    }
}
